// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config")

// Utilities.
const path = require("path")

// Import the RemoveEmptyScriptsPlugin
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts")

// Add any new entry points by extending the webpack config.
module.exports = {
   ...defaultConfig,
   ...{
      entry: {
         "js/gutenbergstore": path.resolve(
            process.cwd(),
            "src/js",
            "gutenberg-store.js"
         ),
         "js/variations": path.resolve(
            process.cwd(),
            "src/js",
            "block-variations.js"
         ),
         "css/editorstyles": path.resolve(
            process.cwd(),
            "src/css",
            "editor-style.css"
         ),
         "css/layouts": path.resolve(process.cwd(), "src/css", "layouts.css"),
      },
      plugins: [
         // Include WP's plugin config.
         ...defaultConfig.plugins,

         // Removes the empty `.js` files generated by webpack but
         // sets it after WP has generated its `*.asset.php` file.
         new RemoveEmptyScriptsPlugin({
            stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
         }),
      ],
   },
}
